import type { CaseStateDef, CaseStateId } from "./types";

/**
 * State catalog — locked copy per PRODUCT_CONTRACT.md §7.
 * EN + HI display strings from day one.
 */
export const STATE_CATALOG: Record<CaseStateId, CaseStateDef> = {
  PAYMENT_EXPECTED: {
    id: "PAYMENT_EXPECTED",
    humanTitle: "We're checking your payment",
    humanTitleHi: "हम आपके भुगतान की जाँच कर रहे हैं",
    humanExplanation: "We're looking at your latest payment status.",
    humanExplanationHi: "हम आपकी नवीनतम भुगतान स्थिति देख रहे हैं।",
    nextActor: "CENTRAL_SYSTEM",
    citizenActionId: null,
    nextStates: ["PAYMENT_CHECK"],
    chain: ["Payment check", "Payment processing", "₹2,000 credited"],
    chainHi: ["भुगतान जाँच", "भुगतान प्रोसेस", "₹2,000 जमा"],
    color: "neutral",
  },
  PAYMENT_CHECK: {
    id: "PAYMENT_CHECK",
    humanTitle: "Checking your case",
    humanTitleHi: "आपके मामले की जाँच हो रही है",
    humanExplanation: "Internal state — resolves in one pass, never shown raw.",
    humanExplanationHi: "आंतरिक स्थिति — एक पास में हल होती है।",
    nextActor: "CENTRAL_SYSTEM",
    citizenActionId: null,
    nextStates: ["PAYMENT_PROCESSING"],
    chain: ["Payment check", "Payment processing", "₹2,000 credited"],
    chainHi: ["भुगतान जाँच", "भुगतान प्रोसेस", "₹2,000 जमा"],
    color: "neutral",
    isInternal: true,
  },
  EKYC_REQUIRED: {
    id: "EKYC_REQUIRED",
    humanTitle: "Your e-KYC needs to be completed",
    humanTitleHi: "आपका ई-केवाईसी पूरा करना आवश्यक है",
    humanExplanation:
      "Your e-KYC must be completed before the payment can proceed. It takes a few minutes through the official PM-KISAN portal or a CSC.",
    humanExplanationHi:
      "भुगतान आगे बढ़ने से पहले आपका ई-केवाईसी पूरा होना ज़रूरी है। आधिकारिक PM-KISAN पोर्टल या CSC के ज़रिए इसमें कुछ मिनट लगते हैं।",
    nextActor: "CITIZEN",
    citizenActionId: "COMPLETE_EKYC",
    nextStates: ["EKYC_VERIFIED"],
    chain: ["e-KYC complete", "Payment processing", "₹2,000 credited"],
    chainHi: ["ई-केवाईसी पूर्ण", "भुगतान प्रोसेस", "₹2,000 जमा"],
    color: "red",
  },
  EKYC_VERIFIED: {
    id: "EKYC_VERIFIED",
    humanTitle: "Your e-KYC is verified",
    humanTitleHi: "आपका ई-केवाईसी सत्यापित हो गया है",
    humanExplanation: "Your case will continue automatically.",
    humanExplanationHi: "आपका मामला अपने आप आगे बढ़ेगा।",
    nextActor: "CENTRAL_SYSTEM",
    citizenActionId: null,
    nextStates: ["PAYMENT_PROCESSING"],
    chain: ["Payment processing", "₹2,000 credited"],
    chainHi: ["भुगतान प्रोसेस", "₹2,000 जमा"],
    color: "neutral",
  },
  PAYMENT_PROCESSING: {
    id: "PAYMENT_PROCESSING",
    humanTitle: "Your payment is being processed",
    humanTitleHi: "आपका भुगतान प्रोसेस हो रहा है",
    humanExplanation: "The payment system is working on your installment.",
    humanExplanationHi: "भुगतान प्रणाली आपकी किस्त पर काम कर रही है।",
    nextActor: "CENTRAL_SYSTEM",
    citizenActionId: null,
    nextStates: ["PAYMENT_CREDITED", "TRANSACTION_FAILED", "PHYSICAL_VERIFICATION_PENDING"],
    chain: ["Payment processing", "₹2,000 credited"],
    chainHi: ["भुगतान प्रोसेस", "₹2,000 जमा"],
    color: "neutral",
  },
  PHYSICAL_VERIFICATION_PENDING: {
    id: "PHYSICAL_VERIFICATION_PENDING",
    humanTitle: "Your benefit is temporarily on hold",
    humanTitleHi: "आपका लाभ अस्थायी रूप से रोका गया है",
    humanExplanation: "Your eligibility is being verified. This is not a rejection.",
    humanExplanationHi: "आपकी पात्रता की जाँच चल रही है। यह अस्वीकृति नहीं है।",
    nextActor: "STATE",
    citizenActionId: null,
    nextStates: ["PAYMENT_PROCESSING", "CITIZEN_ACTION_REQUIRED"],
    chain: ["Eligibility verification", "Payment processing", "₹2,000 credited"],
    chainHi: ["पात्रता जाँच", "भुगतान प्रोसेस", "₹2,000 जमा"],
    color: "amber",
  },
  TRANSACTION_FAILED: {
    id: "TRANSACTION_FAILED",
    humanTitle: "The payment attempt was unsuccessful",
    humanTitleHi: "भुगतान का प्रयास सफल नहीं हो सका",
    humanExplanation:
      "The payment attempt needs further verification. Payment reprocessing — the payment is being processed again after verification.",
    humanExplanationHi:
      "भुगतान के प्रयास को और सत्यापन की ज़रूरत है। भुगतान दोबारा प्रोसेस किया जाएगा — सत्यापन के बाद भुगतान फिर से भेजा जाएगा।",
    nextActor: "STATE",
    citizenActionId: null,
    nextStates: ["PAYMENT_REPROCESSING", "PAYMENT_CREDITED", "CITIZEN_ACTION_REQUIRED"],
    chain: ["State verification", "Payment reprocessing", "Payment processing", "₹2,000 credited"],
    chainHi: ["राज्य सत्यापन", "भुगतान दोबारा प्रोसेस", "भुगतान प्रोसेस", "₹2,000 जमा"],
    color: "amber",
  },
  PAYMENT_REPROCESSING: {
    id: "PAYMENT_REPROCESSING",
    humanTitle: "Your payment is being processed again",
    humanTitleHi: "आपका भुगतान दोबारा प्रोसेस किया जा रहा है",
    humanExplanation: "The payment is being processed again after verification.",
    humanExplanationHi: "सत्यापन के बाद भुगतान फिर से प्रोसेस किया जा रहा है।",
    nextActor: "CENTRAL_SYSTEM",
    citizenActionId: null,
    nextStates: ["PAYMENT_PROCESSING", "PAYMENT_CREDITED", "TRANSACTION_FAILED"],
    chain: ["Payment reprocessing", "Payment processing", "₹2,000 credited"],
    chainHi: ["भुगतान दोबारा प्रोसेस", "भुगतान प्रोसेस", "₹2,000 जमा"],
    color: "neutral",
  },
  CITIZEN_ACTION_REQUIRED: {
    id: "CITIZEN_ACTION_REQUIRED",
    humanTitle: "We need one thing from you",
    humanTitleHi: "हमें आपसे एक काम करना है",
    humanExplanation: "One specific action will move your case forward.",
    humanExplanationHi: "एक विशेष कदम आपके मामले को आगे बढ़ाएगा।",
    nextActor: "CITIZEN",
    citizenActionId: null, // set dynamically by the rules engine per cause
    nextStates: ["PAYMENT_CHECK"],
    chain: ["Your action", "Payment processing", "₹2,000 credited"],
    chainHi: ["आपकी कार्रवाई", "भुगतान प्रोसेस", "₹2,000 जमा"],
    color: "red",
  },
  PAYMENT_CREDITED: {
    id: "PAYMENT_CREDITED",
    humanTitle: "Your payment was credited",
    humanTitleHi: "आपका भुगतान जमा कर दिया गया",
    humanExplanation: "Your PM-KISAN installment was paid to your bank account.",
    humanExplanationHi: "आपकी PM-KISAN किस्त आपके बैंक खाते में जमा कर दी गई है।",
    nextActor: "NONE",
    citizenActionId: null,
    nextStates: [],
    chain: ["Payment credited"],
    chainHi: ["भुगतान जमा"],
    color: "green",
    isTerminal: true,
  },
  RESOLVED: {
    id: "RESOLVED",
    humanTitle: "Your case is resolved",
    humanTitleHi: "आपका मामला हल हो गया है",
    humanExplanation: "There is nothing more you need to do.",
    humanExplanationHi: "आपको अब कुछ और करने की ज़रूरत नहीं है।",
    nextActor: "NONE",
    citizenActionId: null,
    nextStates: [],
    chain: [],
    chainHi: [],
    color: "green",
    isTerminal: true,
  },
};

export const TERMINAL_STATES: CaseStateId[] = ["PAYMENT_CREDITED", "RESOLVED"];
